service: controle-financeiro
frameworkVersion: "2"

custom:
  webpack:
    webpackConfig: "./webpack.config.js" # Name of webpack configuration file
    includeModules:
      forceInclude:
        - mysql2
      forceExclude:
        - aws-sdk
    packager: "npm"
  serverless-offline:
    port: 3000
  contentCompression: 1024
  funcDir: src/4-framework/functions
  baseAPi: api/v1

provider:
  name: aws
  memorySize: 1024
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  timeout: 60
  package:
    excludeDevDependencies: true
    exclude:
      - .git/**
      - .vscode/**
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DATABASE_HOST: "localhost"
    DATABASE_PORT: "33306"
    DATABASE_USER: "admin"
    DATABASE_PASSWORD: "financeiro"
    DATABASE: "financeiro"
    API_KEY: "aXRhw7o="

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  - ${file(${self:custom.funcDir}/auth/_handlers.yml)}
  - ${file(${self:custom.funcDir}/category/_handlers.yml)}
  - ${file(${self:custom.funcDir}/subcategory/_handlers.yml)}
  - ${file(${self:custom.funcDir}/release/_handlers.yml)}
  - ${file(${self:custom.funcDir}/balance/_handlers.yml)}
